// TE-5R1 conservative Air commit using donor-scale + total-pressure scratch.
struct Params { cell_count:u32,threads_x:u32,width:u32,height:u32,chunk_size:u32,chunks_x:u32,chunks_y:u32,sleep_enabled:u32,boundary_mode:u32,_p0:u32,_p1:u32,_p2:u32 };
@group(0) @binding(0) var<uniform> params:Params;@group(0) @binding(1) var<storage,read> material_current:array<u32>;@group(0) @binding(2) var<storage,read> air_mass_current:array<f32>;@group(0) @binding(3) var<storage,read> air_energy_current:array<f32>;@group(0) @binding(4) var<storage,read> donor_scale:array<f32>;@group(0) @binding(5) var<storage,read> total_pressure:array<f32>;@group(0) @binding(6) var<storage,read_write> air_mass_next:array<f32>;@group(0) @binding(7) var<storage,read_write> air_energy_next:array<f32>;@group(0) @binding(8) var<storage,read> chunk_state:array<u32>;
const EMPTY:u32=0u;const SEALED:u32=0u;const STANDARD_MASS:f32=1.0;const STANDARD_ENERGY:f32=293.15;const RATE:f32=0.125;const DEAD:f32=0.001;const SAFETY:f32=0.999999;const MASS_MAX:f32=16.0;const ENERGY_MAX:f32=36370.4;
fn inside(x:i32,y:i32)->bool{return x>=0&&y>=0&&x<i32(params.width)&&y<i32(params.height);}fn at(x:i32,y:i32)->u32{return u32(y)*params.width+u32(x);}fn chunk(i:u32)->u32{return((i/params.width)/params.chunk_size)*params.chunks_x+((i%params.width)/params.chunk_size);}fn face(a:u32,b:u32)->bool{return params.sleep_enabled==0u||chunk_state[chunk(a)]==0u||chunk_state[chunk(b)]==0u;}fn raw(a:f32,b:f32)->f32{return RATE*max(a-b-DEAD,0.0);}fn specific(i:u32)->f32{return select(0.0,air_energy_current[i]/air_mass_current[i],air_mass_current[i]>0.0);}
fn incoming(i:u32,x:i32,y:i32)->vec2<f32>{if(!inside(x,y)){if(params.boundary_mode==SEALED){return vec2(0.0);}let m=raw(1.0,total_pressure[i]);return vec2(m,m*STANDARD_ENERGY);}let n=at(x,y);if(material_current[n]!=EMPTY||!face(i,n)){return vec2(0.0);}let m=raw(total_pressure[n],total_pressure[i]);return vec2(m,m*specific(n));}
fn receiver_scale(i:u32)->f32{let x=i32(i%params.width);let y=i32(i/params.width);let sum=incoming(i,x-1,y)+incoming(i,x+1,y)+incoming(i,x,y-1)+incoming(i,x,y+1);var s=1.0;if(sum.x>0.0){s=min(s,(MASS_MAX-air_mass_current[i])/sum.x);}if(sum.y>0.0){s=min(s,(ENERGY_MAX-air_energy_current[i])/sum.y);}s=clamp(s,0.0,1.0);return select(s,s*SAFETY,s<1.0);}
fn transfer(i:u32,x:i32,y:i32)->vec2<f32>{let own_specific=specific(i);let own_receiver=receiver_scale(i);if(!inside(x,y)){if(params.boundary_mode==SEALED){return vec2(0.0);}let out=raw(total_pressure[i],1.0)*donor_scale[i];let inc=raw(1.0,total_pressure[i])*own_receiver;return vec2(inc-out,inc*STANDARD_ENERGY-out*own_specific);}let n=at(x,y);if(material_current[n]!=EMPTY||!face(i,n)){return vec2(0.0);}let out=raw(total_pressure[i],total_pressure[n])*min(donor_scale[i],receiver_scale(n));let inc=raw(total_pressure[n],total_pressure[i])*min(donor_scale[n],own_receiver);return vec2(inc-out,inc*specific(n)-out*own_specific);}
@compute @workgroup_size(64,1,1) fn air_transport_commit_main(@builtin(global_invocation_id) gid:vec3<u32>){let i=gid.y*params.threads_x+gid.x;if(i>=params.cell_count){return;}if(material_current[i]!=EMPTY){air_mass_next[i]=0.0;air_energy_next[i]=0.0;return;}let x=i32(i%params.width);let y=i32(i/params.width);let d=transfer(i,x-1,y)+transfer(i,x+1,y)+transfer(i,x,y-1)+transfer(i,x,y+1);air_mass_next[i]=air_mass_current[i]+d.x;air_energy_next[i]=air_energy_current[i]+d.y;}
